// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qapp_package.proto

package com.tencent.dolphin.svrcore.qapp;

public final class QAppMsg {
  private QAppMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QAppRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QAppRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    int getVersion();

    /**
     * <code>optional string app_name = 2;</code>
     *
     * <pre>
     *业务名称
     * </pre>
     */
    boolean hasAppName();
    /**
     * <code>optional string app_name = 2;</code>
     *
     * <pre>
     *业务名称
     * </pre>
     */
    java.lang.String getAppName();
    /**
     * <code>optional string app_name = 2;</code>
     *
     * <pre>
     *业务名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>optional string cmd = 3;</code>
     *
     * <pre>
     *请求命令字
     * </pre>
     */
    boolean hasCmd();
    /**
     * <code>optional string cmd = 3;</code>
     *
     * <pre>
     *请求命令字
     * </pre>
     */
    java.lang.String getCmd();
    /**
     * <code>optional string cmd = 3;</code>
     *
     * <pre>
     *请求命令字
     * </pre>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>optional uint64 seq = 4;</code>
     *
     * <pre>
     *请求序列号    
     * </pre>
     */
    boolean hasSeq();
    /**
     * <code>optional uint64 seq = 4;</code>
     *
     * <pre>
     *请求序列号    
     * </pre>
     */
    long getSeq();

    /**
     * <code>optional string client_ip = 5;</code>
     *
     * <pre>
     *客户端ip
     * </pre>
     */
    boolean hasClientIp();
    /**
     * <code>optional string client_ip = 5;</code>
     *
     * <pre>
     *客户端ip
     * </pre>
     */
    java.lang.String getClientIp();
    /**
     * <code>optional string client_ip = 5;</code>
     *
     * <pre>
     *客户端ip
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientIpBytes();

    /**
     * <code>optional string service_ip = 6;</code>
     *
     * <pre>
     *服务端ip
     * </pre>
     */
    boolean hasServiceIp();
    /**
     * <code>optional string service_ip = 6;</code>
     *
     * <pre>
     *服务端ip
     * </pre>
     */
    java.lang.String getServiceIp();
    /**
     * <code>optional string service_ip = 6;</code>
     *
     * <pre>
     *服务端ip
     * </pre>
     */
    com.google.protobuf.ByteString
        getServiceIpBytes();

    /**
     * <code>optional string business = 7;</code>
     *
     * <pre>
     *调用方
     * </pre>
     */
    boolean hasBusiness();
    /**
     * <code>optional string business = 7;</code>
     *
     * <pre>
     *调用方
     * </pre>
     */
    java.lang.String getBusiness();
    /**
     * <code>optional string business = 7;</code>
     *
     * <pre>
     *调用方
     * </pre>
     */
    com.google.protobuf.ByteString
        getBusinessBytes();

    /**
     * <code>optional bytes auth_key = 8;</code>
     *
     * <pre>
     *鉴权key
     * </pre>
     */
    boolean hasAuthKey();
    /**
     * <code>optional bytes auth_key = 8;</code>
     *
     * <pre>
     *鉴权key
     * </pre>
     */
    com.google.protobuf.ByteString getAuthKey();

    /**
     * <code>optional uint32 auth_type = 9;</code>
     *
     * <pre>
     *鉴权类型
     * </pre>
     */
    boolean hasAuthType();
    /**
     * <code>optional uint32 auth_type = 9;</code>
     *
     * <pre>
     *鉴权类型
     * </pre>
     */
    int getAuthType();

    /**
     * <code>optional string auth_ip = 10;</code>
     *
     * <pre>
     *调用方ip
     * </pre>
     */
    boolean hasAuthIp();
    /**
     * <code>optional string auth_ip = 10;</code>
     *
     * <pre>
     *调用方ip
     * </pre>
     */
    java.lang.String getAuthIp();
    /**
     * <code>optional string auth_ip = 10;</code>
     *
     * <pre>
     *调用方ip
     * </pre>
     */
    com.google.protobuf.ByteString
        getAuthIpBytes();

    /**
     * <code>optional uint64 auth_appid = 11;</code>
     *
     * <pre>
     *appid
     * </pre>
     */
    boolean hasAuthAppid();
    /**
     * <code>optional uint64 auth_appid = 11;</code>
     *
     * <pre>
     *appid
     * </pre>
     */
    long getAuthAppid();

    /**
     * <code>optional uint64 uid = 12;</code>
     *
     * <pre>
     *用户唯一标示
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>optional uint64 uid = 12;</code>
     *
     * <pre>
     *用户唯一标示
     * </pre>
     */
    long getUid();

    /**
     * <code>optional bytes body = 13;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 13;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code QAppRequest}
   *
   * <pre>
   *package tencent.im.qapp;
   *应用部&#92;应用平台中心内部通信包协议
   *二进制格式：0x2+htonl(整个包长(4字节))+QAppRequest/QAppResponse+0x3
   * </pre>
   */
  public  static final class QAppRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QAppRequest)
      QAppRequestOrBuilder {
    // Use QAppRequest.newBuilder() to construct.
    private QAppRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private QAppRequest() {
      version_ = 0;
      appName_ = "";
      cmd_ = "";
      seq_ = 0L;
      clientIp_ = "";
      serviceIp_ = "";
      business_ = "";
      authKey_ = com.google.protobuf.ByteString.EMPTY;
      authType_ = 0;
      authIp_ = "";
      authAppid_ = 0L;
      uid_ = 0L;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QAppRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              cmd_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              seq_ = input.readUInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              clientIp_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              serviceIp_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              business_ = bs;
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              authKey_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              authType_ = input.readUInt32();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              authIp_ = bs;
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              authAppid_ = input.readUInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              uid_ = input.readUInt64();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.class, com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    public static final int APP_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object appName_;
    /**
     * <code>optional string app_name = 2;</code>
     *
     * <pre>
     *业务名称
     * </pre>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string app_name = 2;</code>
     *
     * <pre>
     *业务名称
     * </pre>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string app_name = 2;</code>
     *
     * <pre>
     *业务名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private volatile java.lang.Object cmd_;
    /**
     * <code>optional string cmd = 3;</code>
     *
     * <pre>
     *请求命令字
     * </pre>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string cmd = 3;</code>
     *
     * <pre>
     *请求命令字
     * </pre>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cmd = 3;</code>
     *
     * <pre>
     *请求命令字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private long seq_;
    /**
     * <code>optional uint64 seq = 4;</code>
     *
     * <pre>
     *请求序列号    
     * </pre>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 seq = 4;</code>
     *
     * <pre>
     *请求序列号    
     * </pre>
     */
    public long getSeq() {
      return seq_;
    }

    public static final int CLIENT_IP_FIELD_NUMBER = 5;
    private volatile java.lang.Object clientIp_;
    /**
     * <code>optional string client_ip = 5;</code>
     *
     * <pre>
     *客户端ip
     * </pre>
     */
    public boolean hasClientIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string client_ip = 5;</code>
     *
     * <pre>
     *客户端ip
     * </pre>
     */
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string client_ip = 5;</code>
     *
     * <pre>
     *客户端ip
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_IP_FIELD_NUMBER = 6;
    private volatile java.lang.Object serviceIp_;
    /**
     * <code>optional string service_ip = 6;</code>
     *
     * <pre>
     *服务端ip
     * </pre>
     */
    public boolean hasServiceIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string service_ip = 6;</code>
     *
     * <pre>
     *服务端ip
     * </pre>
     */
    public java.lang.String getServiceIp() {
      java.lang.Object ref = serviceIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_ip = 6;</code>
     *
     * <pre>
     *服务端ip
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServiceIpBytes() {
      java.lang.Object ref = serviceIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUSINESS_FIELD_NUMBER = 7;
    private volatile java.lang.Object business_;
    /**
     * <code>optional string business = 7;</code>
     *
     * <pre>
     *调用方
     * </pre>
     */
    public boolean hasBusiness() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string business = 7;</code>
     *
     * <pre>
     *调用方
     * </pre>
     */
    public java.lang.String getBusiness() {
      java.lang.Object ref = business_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          business_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string business = 7;</code>
     *
     * <pre>
     *调用方
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBusinessBytes() {
      java.lang.Object ref = business_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        business_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTH_KEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString authKey_;
    /**
     * <code>optional bytes auth_key = 8;</code>
     *
     * <pre>
     *鉴权key
     * </pre>
     */
    public boolean hasAuthKey() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes auth_key = 8;</code>
     *
     * <pre>
     *鉴权key
     * </pre>
     */
    public com.google.protobuf.ByteString getAuthKey() {
      return authKey_;
    }

    public static final int AUTH_TYPE_FIELD_NUMBER = 9;
    private int authType_;
    /**
     * <code>optional uint32 auth_type = 9;</code>
     *
     * <pre>
     *鉴权类型
     * </pre>
     */
    public boolean hasAuthType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 auth_type = 9;</code>
     *
     * <pre>
     *鉴权类型
     * </pre>
     */
    public int getAuthType() {
      return authType_;
    }

    public static final int AUTH_IP_FIELD_NUMBER = 10;
    private volatile java.lang.Object authIp_;
    /**
     * <code>optional string auth_ip = 10;</code>
     *
     * <pre>
     *调用方ip
     * </pre>
     */
    public boolean hasAuthIp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string auth_ip = 10;</code>
     *
     * <pre>
     *调用方ip
     * </pre>
     */
    public java.lang.String getAuthIp() {
      java.lang.Object ref = authIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string auth_ip = 10;</code>
     *
     * <pre>
     *调用方ip
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAuthIpBytes() {
      java.lang.Object ref = authIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTH_APPID_FIELD_NUMBER = 11;
    private long authAppid_;
    /**
     * <code>optional uint64 auth_appid = 11;</code>
     *
     * <pre>
     *appid
     * </pre>
     */
    public boolean hasAuthAppid() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint64 auth_appid = 11;</code>
     *
     * <pre>
     *appid
     * </pre>
     */
    public long getAuthAppid() {
      return authAppid_;
    }

    public static final int UID_FIELD_NUMBER = 12;
    private long uid_;
    /**
     * <code>optional uint64 uid = 12;</code>
     *
     * <pre>
     *用户唯一标示
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint64 uid = 12;</code>
     *
     * <pre>
     *用户唯一标示
     * </pre>
     */
    public long getUid() {
      return uid_;
    }

    public static final int BODY_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 13;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes body = 13;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, appName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, seq_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, clientIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, serviceIp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, business_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, authKey_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, authType_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, authIp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt64(11, authAppid_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(12, uid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, appName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, seq_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, clientIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, serviceIp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, business_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, authKey_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, authType_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, authIp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, authAppid_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, uid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QAppRequest}
     *
     * <pre>
     *package tencent.im.qapp;
     *应用部&#92;应用平台中心内部通信包协议
     *二进制格式：0x2+htonl(整个包长(4字节))+QAppRequest/QAppResponse+0x3
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QAppRequest)
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.class, com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.Builder.class);
      }

      // Construct using com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        clientIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        serviceIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        business_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        authKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        authType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        authIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        authAppid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppRequest_descriptor;
      }

      public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest getDefaultInstanceForType() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.getDefaultInstance();
      }

      public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest build() {
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest buildPartial() {
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest result = new com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clientIp_ = clientIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.serviceIp_ = serviceIp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.business_ = business_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.authKey_ = authKey_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.authType_ = authType_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.authIp_ = authIp_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.authAppid_ = authAppid_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest) {
          return mergeFrom((com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest other) {
        if (other == com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasAppName()) {
          bitField0_ |= 0x00000002;
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasCmd()) {
          bitField0_ |= 0x00000004;
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasClientIp()) {
          bitField0_ |= 0x00000010;
          clientIp_ = other.clientIp_;
          onChanged();
        }
        if (other.hasServiceIp()) {
          bitField0_ |= 0x00000020;
          serviceIp_ = other.serviceIp_;
          onChanged();
        }
        if (other.hasBusiness()) {
          bitField0_ |= 0x00000040;
          business_ = other.business_;
          onChanged();
        }
        if (other.hasAuthKey()) {
          setAuthKey(other.getAuthKey());
        }
        if (other.hasAuthType()) {
          setAuthType(other.getAuthType());
        }
        if (other.hasAuthIp()) {
          bitField0_ |= 0x00000200;
          authIp_ = other.authIp_;
          onChanged();
        }
        if (other.hasAuthAppid()) {
          setAuthAppid(other.getAuthAppid());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>optional string app_name = 2;</code>
       *
       * <pre>
       *业务名称
       * </pre>
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string app_name = 2;</code>
       *
       * <pre>
       *业务名称
       * </pre>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string app_name = 2;</code>
       *
       * <pre>
       *业务名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string app_name = 2;</code>
       *
       * <pre>
       *业务名称
       * </pre>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_name = 2;</code>
       *
       * <pre>
       *业务名称
       * </pre>
       */
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_name = 2;</code>
       *
       * <pre>
       *业务名称
       * </pre>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>optional string cmd = 3;</code>
       *
       * <pre>
       *请求命令字
       * </pre>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string cmd = 3;</code>
       *
       * <pre>
       *请求命令字
       * </pre>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cmd = 3;</code>
       *
       * <pre>
       *请求命令字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cmd = 3;</code>
       *
       * <pre>
       *请求命令字
       * </pre>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd = 3;</code>
       *
       * <pre>
       *请求命令字
       * </pre>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd = 3;</code>
       *
       * <pre>
       *请求命令字
       * </pre>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <code>optional uint64 seq = 4;</code>
       *
       * <pre>
       *请求序列号    
       * </pre>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 seq = 4;</code>
       *
       * <pre>
       *请求序列号    
       * </pre>
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <code>optional uint64 seq = 4;</code>
       *
       * <pre>
       *请求序列号    
       * </pre>
       */
      public Builder setSeq(long value) {
        bitField0_ |= 0x00000008;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 seq = 4;</code>
       *
       * <pre>
       *请求序列号    
       * </pre>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seq_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object clientIp_ = "";
      /**
       * <code>optional string client_ip = 5;</code>
       *
       * <pre>
       *客户端ip
       * </pre>
       */
      public boolean hasClientIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string client_ip = 5;</code>
       *
       * <pre>
       *客户端ip
       * </pre>
       */
      public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string client_ip = 5;</code>
       *
       * <pre>
       *客户端ip
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string client_ip = 5;</code>
       *
       * <pre>
       *客户端ip
       * </pre>
       */
      public Builder setClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string client_ip = 5;</code>
       *
       * <pre>
       *客户端ip
       * </pre>
       */
      public Builder clearClientIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string client_ip = 5;</code>
       *
       * <pre>
       *客户端ip
       * </pre>
       */
      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceIp_ = "";
      /**
       * <code>optional string service_ip = 6;</code>
       *
       * <pre>
       *服务端ip
       * </pre>
       */
      public boolean hasServiceIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string service_ip = 6;</code>
       *
       * <pre>
       *服务端ip
       * </pre>
       */
      public java.lang.String getServiceIp() {
        java.lang.Object ref = serviceIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service_ip = 6;</code>
       *
       * <pre>
       *服务端ip
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServiceIpBytes() {
        java.lang.Object ref = serviceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_ip = 6;</code>
       *
       * <pre>
       *服务端ip
       * </pre>
       */
      public Builder setServiceIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serviceIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_ip = 6;</code>
       *
       * <pre>
       *服务端ip
       * </pre>
       */
      public Builder clearServiceIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        serviceIp_ = getDefaultInstance().getServiceIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_ip = 6;</code>
       *
       * <pre>
       *服务端ip
       * </pre>
       */
      public Builder setServiceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serviceIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object business_ = "";
      /**
       * <code>optional string business = 7;</code>
       *
       * <pre>
       *调用方
       * </pre>
       */
      public boolean hasBusiness() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string business = 7;</code>
       *
       * <pre>
       *调用方
       * </pre>
       */
      public java.lang.String getBusiness() {
        java.lang.Object ref = business_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            business_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string business = 7;</code>
       *
       * <pre>
       *调用方
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBusinessBytes() {
        java.lang.Object ref = business_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          business_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string business = 7;</code>
       *
       * <pre>
       *调用方
       * </pre>
       */
      public Builder setBusiness(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        business_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string business = 7;</code>
       *
       * <pre>
       *调用方
       * </pre>
       */
      public Builder clearBusiness() {
        bitField0_ = (bitField0_ & ~0x00000040);
        business_ = getDefaultInstance().getBusiness();
        onChanged();
        return this;
      }
      /**
       * <code>optional string business = 7;</code>
       *
       * <pre>
       *调用方
       * </pre>
       */
      public Builder setBusinessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        business_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString authKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes auth_key = 8;</code>
       *
       * <pre>
       *鉴权key
       * </pre>
       */
      public boolean hasAuthKey() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes auth_key = 8;</code>
       *
       * <pre>
       *鉴权key
       * </pre>
       */
      public com.google.protobuf.ByteString getAuthKey() {
        return authKey_;
      }
      /**
       * <code>optional bytes auth_key = 8;</code>
       *
       * <pre>
       *鉴权key
       * </pre>
       */
      public Builder setAuthKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        authKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes auth_key = 8;</code>
       *
       * <pre>
       *鉴权key
       * </pre>
       */
      public Builder clearAuthKey() {
        bitField0_ = (bitField0_ & ~0x00000080);
        authKey_ = getDefaultInstance().getAuthKey();
        onChanged();
        return this;
      }

      private int authType_ ;
      /**
       * <code>optional uint32 auth_type = 9;</code>
       *
       * <pre>
       *鉴权类型
       * </pre>
       */
      public boolean hasAuthType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 auth_type = 9;</code>
       *
       * <pre>
       *鉴权类型
       * </pre>
       */
      public int getAuthType() {
        return authType_;
      }
      /**
       * <code>optional uint32 auth_type = 9;</code>
       *
       * <pre>
       *鉴权类型
       * </pre>
       */
      public Builder setAuthType(int value) {
        bitField0_ |= 0x00000100;
        authType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 auth_type = 9;</code>
       *
       * <pre>
       *鉴权类型
       * </pre>
       */
      public Builder clearAuthType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        authType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object authIp_ = "";
      /**
       * <code>optional string auth_ip = 10;</code>
       *
       * <pre>
       *调用方ip
       * </pre>
       */
      public boolean hasAuthIp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string auth_ip = 10;</code>
       *
       * <pre>
       *调用方ip
       * </pre>
       */
      public java.lang.String getAuthIp() {
        java.lang.Object ref = authIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            authIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string auth_ip = 10;</code>
       *
       * <pre>
       *调用方ip
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAuthIpBytes() {
        java.lang.Object ref = authIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string auth_ip = 10;</code>
       *
       * <pre>
       *调用方ip
       * </pre>
       */
      public Builder setAuthIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        authIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string auth_ip = 10;</code>
       *
       * <pre>
       *调用方ip
       * </pre>
       */
      public Builder clearAuthIp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        authIp_ = getDefaultInstance().getAuthIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string auth_ip = 10;</code>
       *
       * <pre>
       *调用方ip
       * </pre>
       */
      public Builder setAuthIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        authIp_ = value;
        onChanged();
        return this;
      }

      private long authAppid_ ;
      /**
       * <code>optional uint64 auth_appid = 11;</code>
       *
       * <pre>
       *appid
       * </pre>
       */
      public boolean hasAuthAppid() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint64 auth_appid = 11;</code>
       *
       * <pre>
       *appid
       * </pre>
       */
      public long getAuthAppid() {
        return authAppid_;
      }
      /**
       * <code>optional uint64 auth_appid = 11;</code>
       *
       * <pre>
       *appid
       * </pre>
       */
      public Builder setAuthAppid(long value) {
        bitField0_ |= 0x00000400;
        authAppid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 auth_appid = 11;</code>
       *
       * <pre>
       *appid
       * </pre>
       */
      public Builder clearAuthAppid() {
        bitField0_ = (bitField0_ & ~0x00000400);
        authAppid_ = 0L;
        onChanged();
        return this;
      }

      private long uid_ ;
      /**
       * <code>optional uint64 uid = 12;</code>
       *
       * <pre>
       *用户唯一标示
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint64 uid = 12;</code>
       *
       * <pre>
       *用户唯一标示
       * </pre>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>optional uint64 uid = 12;</code>
       *
       * <pre>
       *用户唯一标示
       * </pre>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000800;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 uid = 12;</code>
       *
       * <pre>
       *用户唯一标示
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000800);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 13;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bytes body = 13;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 13;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 13;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00001000);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QAppRequest)
    }

    // @@protoc_insertion_point(class_scope:QAppRequest)
    private static final com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest();
    }

    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QAppRequest>
        PARSER = new com.google.protobuf.AbstractParser<QAppRequest>() {
      public QAppRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new QAppRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<QAppRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QAppRequest> getParserForType() {
      return PARSER;
    }

    public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QAppResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QAppResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 seq = 1;</code>
     *
     * <pre>
     *请求序列号
     * </pre>
     */
    boolean hasSeq();
    /**
     * <code>optional uint64 seq = 1;</code>
     *
     * <pre>
     *请求序列号
     * </pre>
     */
    long getSeq();

    /**
     * <code>optional uint32 err_code = 2;</code>
     *
     * <pre>
     *错误码
     * </pre>
     */
    boolean hasErrCode();
    /**
     * <code>optional uint32 err_code = 2;</code>
     *
     * <pre>
     *错误码
     * </pre>
     */
    int getErrCode();

    /**
     * <code>optional string err_msg = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string err_msg = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string err_msg = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <code>optional bytes body = 4;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 4;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code QAppResponse}
   */
  public  static final class QAppResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QAppResponse)
      QAppResponseOrBuilder {
    // Use QAppResponse.newBuilder() to construct.
    private QAppResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private QAppResponse() {
      seq_ = 0L;
      errCode_ = 0;
      errMsg_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QAppResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seq_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errCode_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errMsg_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.class, com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.Builder.class);
    }

    private int bitField0_;
    public static final int SEQ_FIELD_NUMBER = 1;
    private long seq_;
    /**
     * <code>optional uint64 seq = 1;</code>
     *
     * <pre>
     *请求序列号
     * </pre>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 seq = 1;</code>
     *
     * <pre>
     *请求序列号
     * </pre>
     */
    public long getSeq() {
      return seq_;
    }

    public static final int ERR_CODE_FIELD_NUMBER = 2;
    private int errCode_;
    /**
     * <code>optional uint32 err_code = 2;</code>
     *
     * <pre>
     *错误码
     * </pre>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 err_code = 2;</code>
     *
     * <pre>
     *错误码
     * </pre>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERR_MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errMsg_;
    /**
     * <code>optional string err_msg = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string err_msg = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string err_msg = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 4;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes body = 4;</code>
     *
     * <pre>
     *body
     * </pre>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, errCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, errMsg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, errCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, errMsg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QAppResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QAppResponse)
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.class, com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.Builder.class);
      }

      // Construct using com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.internal_static_QAppResponse_descriptor;
      }

      public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse getDefaultInstanceForType() {
        return com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.getDefaultInstance();
      }

      public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse build() {
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse buildPartial() {
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse result = new com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errMsg_ = errMsg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse) {
          return mergeFrom((com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse other) {
        if (other == com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse.getDefaultInstance()) return this;
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000004;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long seq_ ;
      /**
       * <code>optional uint64 seq = 1;</code>
       *
       * <pre>
       *请求序列号
       * </pre>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 seq = 1;</code>
       *
       * <pre>
       *请求序列号
       * </pre>
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <code>optional uint64 seq = 1;</code>
       *
       * <pre>
       *请求序列号
       * </pre>
       */
      public Builder setSeq(long value) {
        bitField0_ |= 0x00000001;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 seq = 1;</code>
       *
       * <pre>
       *请求序列号
       * </pre>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seq_ = 0L;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional uint32 err_code = 2;</code>
       *
       * <pre>
       *错误码
       * </pre>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 err_code = 2;</code>
       *
       * <pre>
       *错误码
       * </pre>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional uint32 err_code = 2;</code>
       *
       * <pre>
       *错误码
       * </pre>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000002;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 err_code = 2;</code>
       *
       * <pre>
       *错误码
       * </pre>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string err_msg = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string err_msg = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string err_msg = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string err_msg = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string err_msg = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string err_msg = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 4;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes body = 4;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 4;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 4;</code>
       *
       * <pre>
       *body
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QAppResponse)
    }

    // @@protoc_insertion_point(class_scope:QAppResponse)
    private static final com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse();
    }

    public static com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QAppResponse>
        PARSER = new com.google.protobuf.AbstractParser<QAppResponse>() {
      public QAppResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new QAppResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<QAppResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QAppResponse> getParserForType() {
      return PARSER;
    }

    public com.tencent.dolphin.svrcore.qapp.QAppMsg.QAppResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QAppRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QAppRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QAppResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QAppResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022qapp_package.proto\"\350\001\n\013QAppRequest\022\017\n\007" +
      "version\030\001 \001(\r\022\020\n\010app_name\030\002 \001(\t\022\013\n\003cmd\030\003" +
      " \001(\t\022\013\n\003seq\030\004 \001(\004\022\021\n\tclient_ip\030\005 \001(\t\022\022\n\n" +
      "service_ip\030\006 \001(\t\022\020\n\010business\030\007 \001(\t\022\020\n\010au" +
      "th_key\030\010 \001(\014\022\021\n\tauth_type\030\t \001(\r\022\017\n\007auth_" +
      "ip\030\n \001(\t\022\022\n\nauth_appid\030\013 \001(\004\022\013\n\003uid\030\014 \001(" +
      "\004\022\014\n\004body\030\r \001(\014\"L\n\014QAppResponse\022\013\n\003seq\030\001" +
      " \001(\004\022\020\n\010err_code\030\002 \001(\r\022\017\n\007err_msg\030\003 \001(\t\022" +
      "\014\n\004body\030\004 \001(\014B+\n com.tencent.dolphin.svr" +
      "core.qappB\007QAppMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QAppRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QAppRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QAppRequest_descriptor,
        new java.lang.String[] { "Version", "AppName", "Cmd", "Seq", "ClientIp", "ServiceIp", "Business", "AuthKey", "AuthType", "AuthIp", "AuthAppid", "Uid", "Body", });
    internal_static_QAppResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QAppResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QAppResponse_descriptor,
        new java.lang.String[] { "Seq", "ErrCode", "ErrMsg", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
